name: A workflow for my Hello github file
on: push
jobs:
  build:
    name: Hello github action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: 'Darya'
